// <auto-generated />
namespace OmxTechNet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update08042016 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update08042016));
        
        string IMigrationMetadata.Id
        {
            get { return "201604081201154_Update08042016"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
